name: Fix discussions

permissions:
  discussions: write

on:
  push:
    branches:
      - main
    paths:
      - 'src/_posts/**/*.md'

jobs:
  fix-discussions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 2
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
        with:
          node-version: 24
      - run: npm install --no-save @octokit/action
      - run: node .github/actions/fix-discussions.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY_ID: 'DIC_kwDOBNLCjM4ChGfo'
          POSTS_DIR_PATH: 'src/_posts'
          BLOG_URL: 'https://blog.comandeer.pl'
